---
- name: Converge
  hosts: all
  roles:
    - role: ansible.restic
  pre_tasks:
    - name: install bzip2
      package:
        name: bzip2
        state: present
  vars:
    restic_download_path: ~/restic
    restic_install_path: ~/restic
    restic_repos:
      local:
        location: /backup
        password: securepassword1
        init: true
    restic_backups:
      - name: test
        src: /home
        repo: local
        keep_last: 4
        keep_tag: deployment
      - name: test_stdin
        repo: local
        stdin: true
        stdin_cmd: echo "this comes from stdin"
        stdin_filename: stdin.txt
        keep_last: 2
        keep_hourly: 24
        keep_daily: 7
        keep_monthly: 12
        keep_yearly: 5

- name: Converge with dict
  hosts: all
  roles:
    - role: ansible.restic
  pre_tasks:
    - name: install bzip2
      package:
        name: bzip2
        state: present
  vars:
    restic_download_path: ~/restic
    restic_install_path: ~/restic
    restic_repos:
      local:
        location: /backup
        password: securepassword1
        init: true
    restic_backups:
      dicttest:
        name: dicttest
        src: /home
        repo: local
        keep_last: 4
        keep_tag: deployment
